# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: selkies-gstreamer
spec:
  serviceName: selkies-gstreamer
  selector:
    matchLabels:
      app: selkies-gstreamer
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: selkies-gstreamer
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      containers:
        ###
        # selkies-gstreamer selkies-gstreamer container
        ###
        - name: selkies-gstreamer
          image: ghcr.io/selkies-project/selkies-gstreamer/gst-py-example:latest-ubuntu24.04
          imagePullPolicy: Always
          env:
            - name: SELKIES_TURN_REST_URI
              value: "http://coturn-web.coturn.svc.cluster.local:8080"
            - name: SELKIES_TURN_REST_AUTHHEADER
              value: "x-goog-authenticated-user-email"
            - name: SELKIES_TURN_REST_USERNAME
              value: "local:selkies-server"
          ports:
            - name: http-web
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 265Mi
